import type { Product } from "./types";

export const demoProducts: Product[] = [
  {
    id: "SR-REAL-001",
    businessId: "demo-biz-real",
    sku: "SR-REAL-001",
    name: "Traditional Green Kanjivaram Silk Saree",
    description: "Classic temple-border elegance for everyday celebrations.",
    garmentType: "saree",
    category: "one-pieces",
    price: 7999,
    colour: "Emerald Green & Gold",
    colourFamily: "green",
    genderCategory: "women",
    subcategory: "traditional",
    fabric: "Silk",
    pattern: "Temple border",
    occasionTags: ["Festival", "Traditional", "Wedding"],
    styleTags: ["traditional", "royal", "festive"],
    garmentImage: "/products/sarees/SR-REAL-001/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-001/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Kanjivaram",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-001/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-001/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SR-REAL-002",
    businessId: "demo-biz-real",
    sku: "SR-REAL-002",
    name: "Elegant Pink Banarasi Silk Saree",
    description: "Rich Banarasi silk with a refined festive drape.",
    garmentType: "saree",
    category: "one-pieces",
    price: 8999,
    colour: "Rani Pink & Gold",
    colourFamily: "pink",
    genderCategory: "women",
    subcategory: "traditional",
    fabric: "Silk",
    pattern: "Banarasi weave",
    occasionTags: ["Festival", "Wedding", "Party"],
    styleTags: ["royal", "festive", "elevated"],
    garmentImage: "/products/sarees/SR-REAL-002/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-002/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Banarasi",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-002/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-002/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SR-REAL-003",
    businessId: "demo-biz-real",
    sku: "SR-REAL-003",
    name: "Classic Cream Tissue Silk Saree",
    description: "Light-catching tissue silk with classic gold detailing.",
    garmentType: "saree",
    category: "one-pieces",
    price: 6999,
    colour: "Cream & Gold",
    colourFamily: "neutral",
    genderCategory: "women",
    subcategory: "traditional",
    fabric: "Silk",
    pattern: "Tissue weave",
    occasionTags: ["Festival", "Party", "Traditional"],
    styleTags: ["classic", "light", "elegant"],
    garmentImage: "/products/sarees/SR-REAL-003/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-003/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Tissue Silk",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-003/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-003/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SR-REAL-004",
    businessId: "demo-biz-real",
    sku: "SR-REAL-004",
    name: "Royal Purple Embellished Silk Saree",
    description: "A rich purple saree with ornate gold embellishment.",
    garmentType: "saree",
    category: "one-pieces",
    price: 8499,
    colour: "Royal Purple & Gold",
    colourFamily: "purple",
    genderCategory: "women",
    subcategory: "designer",
    fabric: "Silk",
    pattern: "Embellished",
    occasionTags: ["Party", "Wedding", "Traditional"],
    styleTags: ["statement", "designer", "luxury"],
    garmentImage: "/products/sarees/SR-REAL-004/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-004/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Designer",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-004/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-004/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SR-REAL-005",
    businessId: "demo-biz-real",
    sku: "SR-REAL-005",
    name: "Coral Floral Printed Saree",
    description: "A soft coral saree with delicate floral print detailing.",
    garmentType: "saree",
    category: "one-pieces",
    price: 7499,
    colour: "Coral Pink",
    colourFamily: "pink",
    genderCategory: "women",
    subcategory: "printed",
    fabric: "Georgette",
    pattern: "Floral print",
    occasionTags: ["Party", "Casual", "Festival"],
    styleTags: ["floral", "soft", "playful"],
    garmentImage: "/products/sarees/SR-REAL-005/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-005/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Printed",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-005/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-005/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SR-REAL-006",
    businessId: "demo-biz-real",
    sku: "SR-REAL-006",
    name: "Crimson Gold Traditional Saree",
    description: "A statement red saree with classic gold woven borders.",
    garmentType: "saree",
    category: "one-pieces",
    price: 9499,
    colour: "Crimson Red & Gold",
    colourFamily: "red",
    genderCategory: "women",
    subcategory: "traditional",
    fabric: "Silk",
    pattern: "Gold border",
    occasionTags: ["Wedding", "Festival", "Traditional"],
    styleTags: ["grand", "traditional", "bridal"],
    garmentImage: "/products/sarees/SR-REAL-006/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-006/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Banarasi",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-006/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-006/draped.jpg",
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "dress-1",
    businessId: "demo-biz-6",
    sku: "DR-101",
    name: "Classic Red Dress",
    description: "A flattering statement silhouette for evening moments.",
    garmentType: "dress",
    category: "one-pieces",
    price: 4999,
    colour: "Red",
    colourFamily: "red",
    genderCategory: "women",
    subcategory: "evening",
    fabric: "Crepe",
    pattern: "Solid",
    occasionTags: ["Party", "Wedding"],
    styleTags: ["statement", "evening", "modern"],
    garmentImage: "/demo/dress.svg",
    thumbnail: "/demo/dress.svg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SH-REAL-001",
    businessId: "demo-biz-7",
    sku: "SH-REAL-001",
    name: "Premium Checked Shirt",
    description: "Modern clean core with elevated everyday ease.",
    garmentType: "shirt",
    category: "tops",
    price: 2499,
    colour: "Burgundy / Cream",
    colourFamily: "burgundy",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton",
    pattern: "Checked",
    occasionTags: ["Office", "Casual", "Party"],
    styleTags: ["checked", "smart", "versatile", "core"],
    garmentImage: "/products/shirts/SH-REAL-001/main.jpg",
    aiGarmentImage: "/products/shirts/SH-REAL-001/ai.jpg",
    thumbnail: "/products/shirts/SH-REAL-001/thumbnail.jpg",
    drapedReferenceImage: "/products/shirts/SH-REAL-001/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SH-REAL-002",
    businessId: "demo-biz-7",
    sku: "SH-REAL-002",
    name: "Classic Sky Blue Formal Shirt",
    description: "A crisp formal shirt for polished weekday styling.",
    garmentType: "shirt",
    category: "tops",
    price: 2299,
    colour: "Sky Blue",
    colourFamily: "blue",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton",
    pattern: "Solid",
    occasionTags: ["Office", "Casual", "Party"],
    styleTags: ["formal", "smart", "classic"],
    garmentImage: "/products/shirts/SH-REAL-002/main.jpg",
    thumbnail: "/products/shirts/SH-REAL-002/thumbnail.jpg",
    drapedReferenceImage: "/products/shirts/SH-REAL-002/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "SH-REAL-003",
    businessId: "demo-biz-7",
    sku: "SH-REAL-003",
    name: "Premium White Formal Shirt",
    description: "A sharp white shirt with clean formal versatility.",
    garmentType: "shirt",
    category: "tops",
    price: 2499,
    colour: "White",
    colourFamily: "white",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton",
    pattern: "Solid",
    occasionTags: ["Office", "Casual", "Party"],
    styleTags: ["formal", "classic", "versatile"],
    garmentImage: "/products/shirts/SH-REAL-003/main.jpg",
    thumbnail: "/products/shirts/SH-REAL-003/thumbnail.jpg",
    drapedReferenceImage: "/products/shirts/SH-REAL-003/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "TR-REAL-001",
    businessId: "demo-biz-8",
    sku: "TR-REAL-001",
    name: "Classic Navy Formal Trouser",
    description: "Tailored navy trousers for crisp formal combinations.",
    garmentType: "formal-trouser",
    category: "bottoms",
    price: 2999,
    colour: "Navy Blue",
    colourFamily: "navy",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton Blend",
    pattern: "Solid",
    occasionTags: ["Office", "Party", "Casual"],
    styleTags: ["formal", "classic", "tailored"],
    garmentImage: "/products/trousers/TR-REAL-001/main.jpg",
    thumbnail: "/products/trousers/TR-REAL-001/thumbnail.jpg",
    drapedReferenceImage: "/products/trousers/TR-REAL-001/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "TR-REAL-002",
    businessId: "demo-biz-8",
    sku: "TR-REAL-002",
    name: "Premium Black Formal Trouser",
    description: "Premium black trousers for clean formal styling.",
    garmentType: "formal-trouser",
    category: "bottoms",
    price: 2999,
    colour: "Black",
    colourFamily: "black",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton Blend",
    pattern: "Solid",
    occasionTags: ["Office", "Party", "Casual"],
    styleTags: ["formal", "classic", "tailored"],
    garmentImage: "/products/trousers/TR-REAL-002/main.jpg",
    thumbnail: "/products/trousers/TR-REAL-002/thumbnail.jpg",
    drapedReferenceImage: "/products/trousers/TR-REAL-002/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "TR-REAL-003",
    businessId: "demo-biz-8",
    sku: "TR-REAL-003",
    name: "Charcoal Grey Formal Trouser",
    description: "Charcoal formal trousers for refined smart pairings.",
    garmentType: "formal-trouser",
    category: "bottoms",
    price: 3199,
    colour: "Charcoal Grey",
    colourFamily: "charcoal",
    genderCategory: "men",
    subcategory: "formal",
    fabric: "Cotton Blend",
    pattern: "Solid",
    occasionTags: ["Office", "Party", "Casual"],
    styleTags: ["formal", "smart", "tailored"],
    garmentImage: "/products/trousers/TR-REAL-003/main.jpg",
    thumbnail: "/products/trousers/TR-REAL-003/thumbnail.jpg",
    drapedReferenceImage: "/products/trousers/TR-REAL-003/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "TR-REAL-004",
    businessId: "demo-biz-8",
    sku: "TR-REAL-004",
    name: "Beige Smart Chino",
    description: "A beige chino for lighter smart-casual outfits.",
    garmentType: "chino",
    category: "bottoms",
    price: 2799,
    colour: "Beige",
    colourFamily: "beige",
    genderCategory: "men",
    subcategory: "chino",
    fabric: "Cotton Twill",
    pattern: "Solid",
    occasionTags: ["Office", "Casual", "Party"],
    styleTags: ["smart", "casual", "versatile"],
    garmentImage: "/products/trousers/TR-REAL-004/main.jpg",
    thumbnail: "/products/trousers/TR-REAL-004/thumbnail.jpg",
    drapedReferenceImage: "/products/trousers/TR-REAL-004/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
  {
    id: "TR-REAL-005",
    businessId: "demo-biz-8",
    sku: "TR-REAL-005",
    name: "Khaki Casual Chino",
    description: "A relaxed khaki chino for easy casual styling.",
    garmentType: "chino",
    category: "bottoms",
    price: 2799,
    colour: "Khaki",
    colourFamily: "khaki",
    genderCategory: "men",
    subcategory: "chino",
    fabric: "Cotton Twill",
    pattern: "Solid",
    occasionTags: ["Casual", "Office"],
    styleTags: ["casual", "smart", "earthy"],
    garmentImage: "/products/trousers/TR-REAL-005/main.jpg",
    thumbnail: "/products/trousers/TR-REAL-005/thumbnail.jpg",
    drapedReferenceImage: "/products/trousers/TR-REAL-005/draped.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    isTryOnReady: true,
    isRecommendationEligible: true,
  },
];
