import type { Product } from "./types";

export const demoProducts: Product[] = [
  {
    id: "SR-REAL-001",
    businessId: "demo-biz-real",
    sku: "SR-REAL-001",
    name: "Traditional Green Kanjivaram Silk Saree",
    description: "Classic temple-border elegance for everyday celebrations.",
    garmentType: "saree",
    category: "one-pieces",
    price: 7999,
    colour: "Emerald Green & Gold",
    garmentImage: "/products/sarees/SR-REAL-001/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-001/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Kanjivaram",
    fabric: "Silk",
    occasion: "Festival",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-001/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-001/draped.jpg",
  },
  {
    id: "SR-REAL-002",
    businessId: "demo-biz-real",
    sku: "SR-REAL-002",
    name: "Elegant Pink Banarasi Silk Saree",
    description: "Rich Banarasi silk with a refined festive drape.",
    garmentType: "saree",
    category: "one-pieces",
    price: 8999,
    colour: "Rani Pink & Gold",
    garmentImage: "/products/sarees/SR-REAL-002/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-002/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Banarasi",
    fabric: "Silk",
    occasion: "Festival",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-002/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-002/draped.jpg",
  },
  {
    id: "SR-REAL-003",
    businessId: "demo-biz-real",
    sku: "SR-REAL-003",
    name: "Classic Cream Tissue Silk Saree",
    description: "Light-catching tissue silk with classic gold detailing.",
    garmentType: "saree",
    category: "one-pieces",
    price: 6999,
    colour: "Cream & Gold",
    garmentImage: "/products/sarees/SR-REAL-003/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-003/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Tissue Silk",
    fabric: "Silk",
    occasion: "Festival",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-003/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-003/draped.jpg",
  },
  {
    id: "SR-REAL-004",
    businessId: "demo-biz-real",
    sku: "SR-REAL-004",
    name: "Royal Purple Embellished Silk Saree",
    description: "A rich purple saree with ornate gold embellishment.",
    garmentType: "saree",
    category: "one-pieces",
    price: 8499,
    colour: "Royal Purple & Gold",
    garmentImage: "/products/sarees/SR-REAL-004/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-004/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Designer",
    fabric: "Silk",
    occasion: "Party",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-004/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-004/draped.jpg",
  },
  {
    id: "SR-REAL-005",
    businessId: "demo-biz-real",
    sku: "SR-REAL-005",
    name: "Coral Floral Printed Saree",
    description: "A soft coral saree with delicate floral print detailing.",
    garmentType: "saree",
    category: "one-pieces",
    price: 7499,
    colour: "Coral Pink",
    garmentImage: "/products/sarees/SR-REAL-005/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-005/thumbnail.jpg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Printed",
    fabric: "Georgette",
    occasion: "Party",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-005/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-005/draped.jpg",
  },
  {
    id: "SR-REAL-006",
    businessId: "demo-biz-real",
    sku: "SR-REAL-006",
    name: "Crimson Gold Traditional Saree",
    description: "A statement red saree with classic gold woven borders.",
    garmentType: "saree",
    category: "one-pieces",
    price: 9499,
    colour: "Crimson Red & Gold",
    garmentImage: "/products/sarees/SR-REAL-006/main.jpg",
    thumbnail: "/products/sarees/SR-REAL-006/thumbnail.jpg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
    sareeType: "Banarasi",
    fabric: "Silk",
    occasion: "Wedding",
    drapeStyle: "standard-nivi",
    sareeMainImage: "/products/sarees/SR-REAL-006/main.jpg",
    drapedReferenceImage: "/products/sarees/SR-REAL-006/draped.jpg",
  },
  {
    id: "dress-1",
    businessId: "demo-biz-6",
    sku: "DR-101",
    name: "Classic Red Dress",
    description: "A flattering statement silhouette for evening moments.",
    garmentType: "dress",
    category: "one-pieces",
    price: 4999,
    colour: "Red",
    garmentImage: "/demo/dress.svg",
    thumbnail: "/demo/dress.svg",
    featured: true,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "top-1",
    businessId: "demo-biz-7",
    sku: "TP-102",
    name: "Premium Blue Shirt",
    description: "Modern clean core with elevated everyday ease.",
    garmentType: "shirt",
    category: "tops",
    price: 2499,
    colour: "Blue",
    garmentImage: "/demo/top.svg",
    thumbnail: "/demo/top.svg",
    featured: false,
    active: true,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
];
